version: "3.9"

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/htpasswd:/htpasswd
      - ./certs/data:/le # Let's Encrypt certificates
    depends_on:
      - alfa
    environment:
      - TZ=Europe/Warsaw

  alfa:
    container_name: alfa
    image: harbor.cloud.tres.pl/tres-co/alfa:0.1.334
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=alfa_db
      - DB_USER=alfa_user
      - DB_PASSWORD=database_password
      - DB_HOST=postgres
      - DB_PORT=5432
      - ERP_HTTP_ADDRESS=trawers-soa
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=alfa_django_pass
      - DJANGO_SUPERUSER_EMAIL=alfa_superuser_email
      - ALFA_PUBLIC_DOMAIN=replaceme.com
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Europe/Warsaw
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=alfa_db
      - POSTGRES_USER=alfa_user
      - POSTGRES_PASSWORD=database_password
      - TZ=Europe/Warsaw
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    environment:
      - TZ=Europe/Warsaw

  celery-worker:
    image: harbor.cloud.tres.pl/tres-co/alfa:0.1.334
    environment:
      - DB_NAME=alfa_db
      - DB_USER=alfa_user
      - DB_PASSWORD=database_password
      - DB_HOST=postgres
      - DB_PORT=5432
      - ERP_HTTP_ADDRESS=trawers-soa
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=alfa_django_pass
      - DJANGO_SUPERUSER_EMAIL=alfa_superuser_email
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Europe/Warsaw
      - CELERY_BROKER=redis://redis:6379/0
    entrypoint: ['celery','-A','alfa','worker','-l','info']
    depends_on:
      - postgres
      - redis

  celery-beat:
    image: harbor.cloud.tres.pl/tres-co/alfa:0.1.334
    environment:
      - DB_NAME=alfa_db
      - DB_USER=alfa_user
      - DB_PASSWORD=database_password
      - DB_HOST=postgres
      - DB_PORT=5432
      - ERP_HTTP_ADDRESS=trawers-soa
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=alfa_django_pass
      - DJANGO_SUPERUSER_EMAIL=alfa_superuser_email
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Europe/Warsaw
      - CELERY_BROKER=redis://redis:6379/0
    entrypoint: ['celery','-A','alfa','beat','-l','info']
    depends_on:
      - postgres
      - redis

  trawers-soa:
    image: harbor.cloud.tres.pl/tres-co/ssh-client:0.1.2
    volumes:
      - ./soa_key:/soa_key
    command: ssh -v -o StrictHostKeyChecking=no -L 0.0.0.0:7000:192.168.0.12:7000 -i /soa_key -p 22 user@10.20.30.40  -- sleep infinity
